---
ID: "1341f47a-b09a-4016-a642-ab36de4fb94f"
Parent: "2ea3127f-37b6-44af-a4aa-022d27dda9a5"
Template: "98e60957-0783-4a9a-85cc-77dad30e9711"
Path: "/sitecore/content/industry-verticals/baptist-health/Home/Services"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C0274E9D-2974-4766-A29A-0C4F9FAF8C86}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{9DE6FB43-4D3E-4D68-A15B-01FB7D71E4B3}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "026b198e-80c7-43fa-b7a7-15c48da83940"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{30ACA572-3C1B-494E-B907-D96F014B8CDB}"
          s:ds="E17E6567-56A0-4517-98AE-23B069765F75"
          s:id="{E3CCF1D0-7855-4898-8BDE-77F83C6A487C}"
          s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BACAE8592-E847-4AD7-920B-E210A1B027AE%7D&amp;Styles=%7C%7B46800F5D-4AC8-4E82-9E9D-0EA3CA71AD1B%7D&amp;RenderingIdentifier&amp;CSSStyles"
          s:ph="headless-main" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "e445c8b5-5412-4a05-8bb5-f40f3be6d07d"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{E8C94B8B-CD55-47A8-9F38-3DD712CAC7AC}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T074821Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "4ff91248-33ab-4254-b6f7-2618fd0aebae"
      Hint: Title
      Value: Services
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1f8ed4a0-7d81-4b77-926a-95dd2e496dfd"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\zach.escabedo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260225T153320Z
- Language: "es-PR"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "85c5c194-ca4c-471f-84a2-a526cf1fbfb0"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Servicios
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{E8C94B8B-CD55-47A8-9F38-3DD712CAC7AC}">
              <p:d />
            </r>
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251117T074821Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Servicios
    - ID: "4ff91248-33ab-4254-b6f7-2618fd0aebae"
      Hint: Title
      Value: Servicios
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "113f475b-b0b0-4c1c-b640-6e4164ab9024"
    - ID: "9857f526-390f-48df-b6d1-1a97cc328e8f"
      Hint: __Version Name
      Value: AI translated
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\yuri.yampolsky@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260226T060901Z
