// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Link, Text, useSitecore, RichText, NextImage, Image, DateField, Placeholder, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import { useMemo, useState, useCallback, useRef, useEffect } from 'react';
import React from 'react';
import Head from 'next/head';
import { useI18n } from 'next-localization';
import { faFacebookF, faInstagram, faLinkedinIn, faTwitter, faYoutube, faPinterestP } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { ArrowRight, Share2, ArrowLeft, ChevronLeft, ChevronRight, Phone, Plane, Bed, Camera, Navigation, CalendarDays, Clock, MapPin, Star, Thermometer, LoaderCircle, Check, ChevronDown, X, Search, Users, Menu, Heart, Calendar, User } from 'lucide-react';
import * as LucidIcons from 'lucide-react';
import { LayoutStyles, PromoFlags, HeroBannerStyles, TitleSectionFlags } from '@/types/styleFlags';
import { newsDateFormatter } from '@/helpers/dateHelper';
import { useSearchParams, usePathname, useRouter } from 'next/navigation';
import QuestionsAnswers from 'src/components/non-sitecore/search/QuestionsAnswers';
import SearchResultsWidget from 'src/components/non-sitecore/search/SearchResultsComponent';
import { SEARCH_WIDGET_ID, HIGHLIGHTED_ARTICLES_RFKID, DEFAULT_IMG_URL, PREVIEW_WIDGET_ID, HOMEHIGHLIGHTED_WIDGET_ID, DESTINATIONS_WIDGET_ID } from '@/constants/search';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/shadcn/components/ui/dropdown-menu';
import { faEnvelope } from '@fortawesome/free-solid-svg-icons';
import { EmailIcon, EmailShareButton, FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, PinterestIcon, PinterestShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import { usePagination } from '@/hooks/usePagination';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/shadcn/components/ui/tabs';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import { usePreviewSearchActions, useSearchResultsActions, WidgetDataType, useSearchResults, widget, useQuestions, usePreviewSearch, FilterEqual, useSearchResultsSelectedFacets } from '@sitecore-search/react';
import { PreviewSearch, SortSelect, Pagination, AccordionFacets, FacetItem, RangeFacet, SearchResultsAccordionFacets, SearchResultsFacetValueRange, Select, ArticleCard, CardViewSwitcher as CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 } from '@sitecore-search/ui';
import { GridIcon, ListBulletIcon, CheckIcon, ChevronDownIcon } from '@radix-ui/react-icons';
import HomeHighlighted from 'src/components/non-sitecore/search/HomeHighlighted';
import Spinner from 'src/components/non-sitecore/search/Spinner';
import ArticleItemCard from 'src/components/non-sitecore/search/ArticleCard';
import SortOrder from 'src/components/non-sitecore/search/SortOrder';
import ArticleHorizontalItemCard from 'src/components/non-sitecore/search/ArticleHorizontalCard';
import SearchPagination from 'src/components/non-sitecore/search/SearchPagination';
import SearchFacets from 'src/components/non-sitecore/search/SearchFacets';
import ResultsPerPage from 'src/components/non-sitecore/search/ResultsPerPage';
import QueryResultsSummary from 'src/components/non-sitecore/search/QueryResultsSummary';
import CardViewSwitcher from 'src/components/non-sitecore/search/CardViewSwitcher';
import { useSearchTracking } from '@/hooks/useSearchTracking';
import { Accordion, Content, Header, Item, Trigger } from '@radix-ui/react-accordion';
import SuggestionBlock from 'src/components/non-sitecore/search/SuggestionBlock';
import { useClickAway } from '@/hooks/useClickAway';
import { useStopResponsiveTransition } from '@/hooks/useStopResponsiveTransition';
import { extractMediaUrl } from '@/helpers/extractMediaUrl';
import { getLinkContent, getLinkField, isNavLevel, isNavRootItem, prepareFields } from '@/helpers/navHelpers';
import clsx from 'clsx';
import { isParamEnabled } from '@/helpers/isParamEnabled';
import { Drawer, DrawerTrigger, DrawerContent, DrawerClose } from '@/shadcn/components/ui/drawer';
import { DatePicker } from '@/shadcn/components/ui/date-picker';
import PreviewSearch_938f3b0320996fc3fe6ab3d953daf2e708e085ca from 'src/components/non-sitecore/search/PreviewSearch';
import DestinationCard from 'src/components/non-sitecore/DestinationCard';
import FilterDropdown from 'src/components/non-sitecore/search/FilterDropdown';
import SocialShare from 'src/components/non-sitecore/SocialShare';
import { DestinationHighlights } from 'src/components/non-sitecore/DestinationHighlights';
import { DestinationSidebar } from 'src/components/non-sitecore/DestinationSidebar';
import { ParentPathLink } from 'src/components/non-sitecore/ParentPathLink';
import { DestinationLinkedContent } from 'src/components/non-sitecore/DestinationLinkedContent';
import client from 'lib/sitecore-client';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { newsDateFormatter as newsDateFormatter_77fef27f114da656b11a70d96f9a0ef7725fc8c6 } from 'src/helpers/dateHelper';
import { Author } from 'src/components/non-sitecore/Author';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'Image', value: Image },
      { name: 'DateField', value: DateField },
      { name: 'Placeholder', value: Placeholder },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useMemo', value: useMemo },
      { name: 'useState', value: useState },
      { name: 'useCallback', value: useCallback },
      { name: 'useRef', value: useRef },
      { name: 'useEffect', value: useEffect },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: '@fortawesome/free-brands-svg-icons',
    exports: [
      { name: 'faFacebookF', value: faFacebookF },
      { name: 'faInstagram', value: faInstagram },
      { name: 'faLinkedinIn', value: faLinkedinIn },
      { name: 'faTwitter', value: faTwitter },
      { name: 'faYoutube', value: faYoutube },
      { name: 'faPinterestP', value: faPinterestP },
    ]
  },
  {
    module: '@fortawesome/react-fontawesome',
    exports: [
      { name: 'FontAwesomeIcon', value: FontAwesomeIcon },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'ArrowRight', value: ArrowRight },
      { name: 'Share2', value: Share2 },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'ChevronRight', value: ChevronRight },
      { name: 'Phone', value: Phone },
      { name: 'Plane', value: Plane },
      { name: 'Bed', value: Bed },
      { name: 'Camera', value: Camera },
      { name: 'Navigation', value: Navigation },
      { name: 'CalendarDays', value: CalendarDays },
      { name: 'Clock', value: Clock },
      { name: 'MapPin', value: MapPin },
      { name: 'Star', value: Star },
      { name: 'Thermometer', value: Thermometer },
      { name: 'LoaderCircle', value: LoaderCircle },
      { name: 'Check', value: Check },
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'X', value: X },
      { name: 'Search', value: Search },
      { name: 'Users', value: Users },
      { name: 'Menu', value: Menu },
      { name: 'Heart', value: Heart },
      { name: 'Calendar', value: Calendar },
      { name: 'User', value: User },
      { name: '*', value: LucidIcons },
    ]
  },
  {
    module: '@/types/styleFlags',
    exports: [
      { name: 'LayoutStyles', value: LayoutStyles },
      { name: 'PromoFlags', value: PromoFlags },
      { name: 'HeroBannerStyles', value: HeroBannerStyles },
      { name: 'TitleSectionFlags', value: TitleSectionFlags },
    ]
  },
  {
    module: '@/helpers/dateHelper',
    exports: [
      { name: 'newsDateFormatter', value: newsDateFormatter },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'useSearchParams', value: useSearchParams },
      { name: 'usePathname', value: usePathname },
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/QuestionsAnswers',
    exports: [
      { name: 'default', value: QuestionsAnswers },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/SearchResultsComponent',
    exports: [
      { name: 'default', value: SearchResultsWidget },
    ]
  },
  {
    module: '@/constants/search',
    exports: [
      { name: 'SEARCH_WIDGET_ID', value: SEARCH_WIDGET_ID },
      { name: 'HIGHLIGHTED_ARTICLES_RFKID', value: HIGHLIGHTED_ARTICLES_RFKID },
      { name: 'DEFAULT_IMG_URL', value: DEFAULT_IMG_URL },
      { name: 'PREVIEW_WIDGET_ID', value: PREVIEW_WIDGET_ID },
      { name: 'HOMEHIGHLIGHTED_WIDGET_ID', value: HOMEHIGHLIGHTED_WIDGET_ID },
      { name: 'DESTINATIONS_WIDGET_ID', value: DESTINATIONS_WIDGET_ID },
    ]
  },
  {
    module: '@/shadcn/components/ui/dropdown-menu',
    exports: [
      { name: 'DropdownMenu', value: DropdownMenu },
      { name: 'DropdownMenuContent', value: DropdownMenuContent },
      { name: 'DropdownMenuItem', value: DropdownMenuItem },
      { name: 'DropdownMenuTrigger', value: DropdownMenuTrigger },
    ]
  },
  {
    module: '@fortawesome/free-solid-svg-icons',
    exports: [
      { name: 'faEnvelope', value: faEnvelope },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'EmailIcon', value: EmailIcon },
      { name: 'EmailShareButton', value: EmailShareButton },
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'PinterestIcon', value: PinterestIcon },
      { name: 'PinterestShareButton', value: PinterestShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: '@/hooks/usePagination',
    exports: [
      { name: 'usePagination', value: usePagination },
    ]
  },
  {
    module: '@/shadcn/components/ui/tabs',
    exports: [
      { name: 'Tabs', value: Tabs },
      { name: 'TabsContent', value: TabsContent },
      { name: 'TabsList', value: TabsList },
      { name: 'TabsTrigger', value: TabsTrigger },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'usePreviewSearchActions', value: usePreviewSearchActions },
      { name: 'useSearchResultsActions', value: useSearchResultsActions },
      { name: 'WidgetDataType', value: WidgetDataType },
      { name: 'useSearchResults', value: useSearchResults },
      { name: 'widget', value: widget },
      { name: 'useQuestions', value: useQuestions },
      { name: 'usePreviewSearch', value: usePreviewSearch },
      { name: 'FilterEqual', value: FilterEqual },
      { name: 'useSearchResultsSelectedFacets', value: useSearchResultsSelectedFacets },
    ]
  },
  {
    module: '@sitecore-search/ui',
    exports: [
      { name: 'PreviewSearch', value: PreviewSearch },
      { name: 'SortSelect', value: SortSelect },
      { name: 'Pagination', value: Pagination },
      { name: 'AccordionFacets', value: AccordionFacets },
      { name: 'FacetItem', value: FacetItem },
      { name: 'RangeFacet', value: RangeFacet },
      { name: 'SearchResultsAccordionFacets', value: SearchResultsAccordionFacets },
      { name: 'SearchResultsFacetValueRange', value: SearchResultsFacetValueRange },
      { name: 'Select', value: Select },
      { name: 'ArticleCard', value: ArticleCard },
      { name: 'CardViewSwitcher', value: CardViewSwitcher_b6c381477cbf12fc0dc4f9aeb9e8e41e943b6ea7 },
    ]
  },
  {
    module: '@radix-ui/react-icons',
    exports: [
      { name: 'GridIcon', value: GridIcon },
      { name: 'ListBulletIcon', value: ListBulletIcon },
      { name: 'CheckIcon', value: CheckIcon },
      { name: 'ChevronDownIcon', value: ChevronDownIcon },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/HomeHighlighted',
    exports: [
      { name: 'default', value: HomeHighlighted },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/Spinner',
    exports: [
      { name: 'default', value: Spinner },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/ArticleCard',
    exports: [
      { name: 'default', value: ArticleItemCard },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/SortOrder',
    exports: [
      { name: 'default', value: SortOrder },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/ArticleHorizontalCard',
    exports: [
      { name: 'default', value: ArticleHorizontalItemCard },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/SearchPagination',
    exports: [
      { name: 'default', value: SearchPagination },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/SearchFacets',
    exports: [
      { name: 'default', value: SearchFacets },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/ResultsPerPage',
    exports: [
      { name: 'default', value: ResultsPerPage },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/QueryResultsSummary',
    exports: [
      { name: 'default', value: QueryResultsSummary },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/CardViewSwitcher',
    exports: [
      { name: 'default', value: CardViewSwitcher },
    ]
  },
  {
    module: '@/hooks/useSearchTracking',
    exports: [
      { name: 'useSearchTracking', value: useSearchTracking },
    ]
  },
  {
    module: '@radix-ui/react-accordion',
    exports: [
      { name: 'Accordion', value: Accordion },
      { name: 'Content', value: Content },
      { name: 'Header', value: Header },
      { name: 'Item', value: Item },
      { name: 'Trigger', value: Trigger },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/SuggestionBlock',
    exports: [
      { name: 'default', value: SuggestionBlock },
    ]
  },
  {
    module: '@/hooks/useClickAway',
    exports: [
      { name: 'useClickAway', value: useClickAway },
    ]
  },
  {
    module: '@/hooks/useStopResponsiveTransition',
    exports: [
      { name: 'useStopResponsiveTransition', value: useStopResponsiveTransition },
    ]
  },
  {
    module: '@/helpers/extractMediaUrl',
    exports: [
      { name: 'extractMediaUrl', value: extractMediaUrl },
    ]
  },
  {
    module: '@/helpers/navHelpers',
    exports: [
      { name: 'getLinkContent', value: getLinkContent },
      { name: 'getLinkField', value: getLinkField },
      { name: 'isNavLevel', value: isNavLevel },
      { name: 'isNavRootItem', value: isNavRootItem },
      { name: 'prepareFields', value: prepareFields },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'default', value: clsx },
    ]
  },
  {
    module: '@/helpers/isParamEnabled',
    exports: [
      { name: 'isParamEnabled', value: isParamEnabled },
    ]
  },
  {
    module: '@/shadcn/components/ui/drawer',
    exports: [
      { name: 'Drawer', value: Drawer },
      { name: 'DrawerTrigger', value: DrawerTrigger },
      { name: 'DrawerContent', value: DrawerContent },
      { name: 'DrawerClose', value: DrawerClose },
    ]
  },
  {
    module: '@/shadcn/components/ui/date-picker',
    exports: [
      { name: 'DatePicker', value: DatePicker },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/PreviewSearch',
    exports: [
      { name: 'default', value: PreviewSearch_938f3b0320996fc3fe6ab3d953daf2e708e085ca },
    ]
  },
  {
    module: 'src/components/non-sitecore/DestinationCard',
    exports: [
      { name: 'default', value: DestinationCard },
    ]
  },
  {
    module: 'src/components/non-sitecore/search/FilterDropdown',
    exports: [
      { name: 'default', value: FilterDropdown },
    ]
  },
  {
    module: 'src/components/non-sitecore/SocialShare',
    exports: [
      { name: 'default', value: SocialShare },
    ]
  },
  {
    module: 'src/components/non-sitecore/DestinationHighlights',
    exports: [
      { name: 'DestinationHighlights', value: DestinationHighlights },
    ]
  },
  {
    module: 'src/components/non-sitecore/DestinationSidebar',
    exports: [
      { name: 'DestinationSidebar', value: DestinationSidebar },
    ]
  },
  {
    module: 'src/components/non-sitecore/ParentPathLink',
    exports: [
      { name: 'ParentPathLink', value: ParentPathLink },
    ]
  },
  {
    module: 'src/components/non-sitecore/DestinationLinkedContent',
    exports: [
      { name: 'DestinationLinkedContent', value: DestinationLinkedContent },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'src/helpers/dateHelper',
    exports: [
      { name: 'newsDateFormatter', value: newsDateFormatter_77fef27f114da656b11a70d96f9a0ef7725fc8c6 },
    ]
  },
  {
    module: 'src/components/non-sitecore/Author',
    exports: [
      { name: 'Author', value: Author },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
