#!/usr/bin/env sh
set -e
set -o pipefail

# ensure we run from the app folder
cd "$(git rev-parse --show-toplevel)/industry-verticals/retail"

# (optional) trace
echo ">> pre-commit running in $(pwd)"

# run your checks
npx tsc -p tsconfig.json --noEmit
npx lint-staged
